package com.aitrainercrm.platform.invoice.entity;

import com.aitrainercrm.platform.common.entity.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * A bill for exactly one {@link com.aitrainercrm.platform.order.entity.Order}
 * (see {@link #orderId}), generated by {@code InvoiceService#generateFromOrder}
 * - unlike {@code Order.quoteId}, this link is required: an invoice always
 * traces back to the order it bills for. Same shared-org-resource pattern as
 * {@code Order}/{@code Product} - no {@code ownerId}, no per-record
 * ScopeAuthorizationService check.
 *
 * <p>{@link #status} moves DRAFT -&gt; SENT -&gt; PAID, with VOID reachable from
 * DRAFT or SENT (not from PAID - see {@code InvoiceService#voidInvoice}).
 * DRAFT -&gt; SENT is gated on {@code INVOICE:APPROVE}, the same "sign off on
 * it" pattern as {@code Order}'s DRAFT -&gt; CONFIRMED; SENT -&gt; PAID happens
 * automatically, driven by {@code PaymentService} whenever recorded payments
 * cover {@link #totalAmount} (never set directly through this module's own
 * update endpoints). OVERDUE exists in the enum for a dashboard/report to
 * set based on {@link #dueDate} having passed, but nothing in this module
 * flips it automatically - there's no scheduled job here, deliberately, to
 * keep this module's scope to the order-to-cash flow itself.
 *
 * <p>{@link #subtotal}/{@link #totalAmount}/{@link #amountPaid} are all
 * stamped columns - the first two recomputed by {@code InvoiceService} on
 * every line item change, {@code amountPaid} recomputed by
 * {@code PaymentService} on every payment recorded or removed.
 */
@Entity
@Table(name = "invoices")
@Getter
@Setter
@NoArgsConstructor
public class Invoice extends BaseEntity {

    public enum Status {
        DRAFT, SENT, PAID, OVERDUE, VOID
    }

    @Column(name = "organization_id", nullable = false)
    private UUID organizationId;

    @Column(name = "order_id", nullable = false)
    private UUID orderId;

    @Column(name = "invoice_number", nullable = false, length = 50)
    private String invoiceNumber;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Status status = Status.DRAFT;

    @Column(length = 3)
    private String currency;

    @Column(name = "issue_date", nullable = false)
    private LocalDate issueDate;

    @Column(name = "due_date", nullable = false)
    private LocalDate dueDate;

    @Column(nullable = false, precision = 14, scale = 2)
    private BigDecimal subtotal = BigDecimal.ZERO;

    @Column(name = "discount_amount", nullable = false, precision = 14, scale = 2)
    private BigDecimal discountAmount = BigDecimal.ZERO;

    @Column(name = "tax_amount", nullable = false, precision = 14, scale = 2)
    private BigDecimal taxAmount = BigDecimal.ZERO;

    @Column(name = "total_amount", nullable = false, precision = 14, scale = 2)
    private BigDecimal totalAmount = BigDecimal.ZERO;

    @Column(name = "amount_paid", nullable = false, precision = 14, scale = 2)
    private BigDecimal amountPaid = BigDecimal.ZERO;

    @Column(name = "deleted_at")
    private Instant deletedAt;

    public Invoice(UUID organizationId, UUID orderId, String invoiceNumber, LocalDate issueDate, LocalDate dueDate) {
        this.organizationId = organizationId;
        this.orderId = orderId;
        this.invoiceNumber = invoiceNumber;
        this.issueDate = issueDate;
        this.dueDate = dueDate;
    }

    public boolean isDeleted() {
        return deletedAt != null;
    }

    /** totalAmount - amountPaid, floored at zero (a rounding-driven tiny overpayment shouldn't show as a negative balance). */
    public BigDecimal balanceDue() {
        BigDecimal balance = totalAmount.subtract(amountPaid);
        return balance.signum() < 0 ? BigDecimal.ZERO : balance;
    }
}
