package com.aitrainercrm.platform.attachment.storage;

import com.aitrainercrm.platform.config.StorageProperties;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;
import org.springframework.stereotype.Service;

/**
 * Default {@link FileStorageService}: writes under {@code crm.storage.upload-dir}
 * (default {@code ./uploads}, override via {@code STORAGE_UPLOAD_DIR}) on whatever
 * filesystem the application process is running on. This is a genuinely working
 * implementation, not a stub like {@code LoggingEmailService} - files really are
 * written and read back - but it comes with a real production limitation worth being
 * honest about: local disk isn't shared across container replicas and isn't durable
 * across a redeploy unless {@code upload-dir} is a mounted volume. That tradeoff is
 * fine for a single-instance/dev deployment; a multi-replica production deployment
 * should implement {@link FileStorageService} against S3/GCS instead and swap the
 * Spring bean - no change needed anywhere else, including {@code AttachmentService}.
 */
@Service
public class LocalFileStorageService implements FileStorageService {

    private final Path root;

    public LocalFileStorageService(StorageProperties properties) {
        this.root = Path.of(properties.uploadDir()).toAbsolutePath().normalize();
        try {
            Files.createDirectories(root);
        } catch (IOException e) {
            throw new AttachmentStorageException("Could not create upload directory: " + root, e);
        }
    }

    @Override
    public String store(UUID organizationId, String originalFileName, byte[] content) {
        String key = organizationId + "/" + UUID.randomUUID() + "-" + sanitize(originalFileName);
        Path target = resolve(key);
        try {
            Files.createDirectories(target.getParent());
            Files.write(target, content);
        } catch (IOException e) {
            throw new AttachmentStorageException("Could not store file", e);
        }
        return key;
    }

    @Override
    public byte[] retrieve(String storageKey) {
        try {
            return Files.readAllBytes(resolve(storageKey));
        } catch (IOException e) {
            throw new AttachmentStorageException("Could not read stored file", e);
        }
    }

    @Override
    public void delete(String storageKey) {
        try {
            Files.deleteIfExists(resolve(storageKey));
        } catch (IOException e) {
            throw new AttachmentStorageException("Could not delete stored file", e);
        }
    }

    /** Guards against path traversal via a crafted storageKey - defense in depth, since keys are generated by {@link #store} and never accepted directly from a client, but cheap insurance against a future caller that doesn't hold that invariant. */
    private Path resolve(String storageKey) {
        Path resolved = root.resolve(storageKey).normalize();
        if (!resolved.startsWith(root)) {
            throw new IllegalArgumentException("Invalid storage key");
        }
        return resolved;
    }

    private String sanitize(String fileName) {
        String base = fileName == null ? "file" : fileName.replaceAll("[^a-zA-Z0-9._-]", "_");
        return base.isBlank() ? "file" : base;
    }
}
